services:
  db:
    image: postgres:15
    container_name: expense_db
    restart: always
    environment:
      POSTGRES_USER: arya
      POSTGRES_PASSWORD: arya
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
